/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_seeta_sdk_FaceDetector */

#ifndef _Included_com_seeta_sdk_FaceDetector
#define _Included_com_seeta_sdk_FaceDetector
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_seeta_sdk_FaceDetector
 * Method:    construct
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_seeta_sdk_FaceDetector_construct__Ljava_lang_String_2
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_seeta_sdk_FaceDetector
 * Method:    construct
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_seeta_sdk_FaceDetector_construct__Ljava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_seeta_sdk_FaceDetector
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_seeta_sdk_FaceDetector_dispose
  (JNIEnv *, jobject);

/*
 * Class:     com_seeta_sdk_FaceDetector
 * Method:    Detect
 * Signature: (Lcom/seeta/sdk/ImageData;)[Lcom/seeta/sdk/FaceInfo;
 */
JNIEXPORT jobjectArray JNICALL Java_com_seeta_sdk_FaceDetector_Detect
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_seeta_sdk_FaceDetector
 * Method:    SetMinFaceSize
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_seeta_sdk_FaceDetector_SetMinFaceSize
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_seeta_sdk_FaceDetector
 * Method:    SetImagePyramidScaleFactor
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_seeta_sdk_FaceDetector_SetImagePyramidScaleFactor
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_seeta_sdk_FaceDetector
 * Method:    SetScoreThresh
 * Signature: (FFF)V
 */
JNIEXPORT void JNICALL Java_com_seeta_sdk_FaceDetector_SetScoreThresh
  (JNIEnv *, jobject, jfloat, jfloat, jfloat);

/*
 * Class:     com_seeta_sdk_FaceDetector
 * Method:    SetVideoStable
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_seeta_sdk_FaceDetector_SetVideoStable
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_seeta_sdk_FaceDetector
 * Method:    GetVideoStable
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_seeta_sdk_FaceDetector_GetVideoStable
  (JNIEnv *, jobject);

/*
 * Class:     com_seeta_sdk_FaceDetector
 * Method:    SetNumThreads
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_seeta_sdk_FaceDetector_SetNumThreads
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
