/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_seeta_sdk_EyeBlinkDetector */

#ifndef _Included_com_seeta_sdk_EyeBlinkDetector
#define _Included_com_seeta_sdk_EyeBlinkDetector
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_seeta_sdk_EyeBlinkDetector
 * Method:    construct
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_seeta_sdk_EyeBlinkDetector_construct__Ljava_lang_String_2
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_seeta_sdk_EyeBlinkDetector
 * Method:    construct
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_seeta_sdk_EyeBlinkDetector_construct__Ljava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_seeta_sdk_EyeBlinkDetector
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_seeta_sdk_EyeBlinkDetector_dispose
  (JNIEnv *, jobject);

/*
 * Class:     com_seeta_sdk_EyeBlinkDetector
 * Method:    Detect
 * Signature: (Lcom/seeta/sdk/ImageData;[Lcom/seeta/sdk/Point;)I
 */
JNIEXPORT jint JNICALL Java_com_seeta_sdk_EyeBlinkDetector_Detect
  (JNIEnv *, jobject, jobject, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
