/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_seeta_sdk_PointDetector */

#ifndef _Included_com_seeta_sdk_PointDetector
#define _Included_com_seeta_sdk_PointDetector
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_seeta_sdk_PointDetector
 * Method:    construct
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_seeta_sdk_PointDetector_construct
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_seeta_sdk_PointDetector
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_seeta_sdk_PointDetector_dispose
  (JNIEnv *, jobject);

/*
 * Class:     com_seeta_sdk_PointDetector
 * Method:    LoadModel
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_seeta_sdk_PointDetector_LoadModel
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_seeta_sdk_PointDetector
 * Method:    SetStable
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_seeta_sdk_PointDetector_SetStable
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_seeta_sdk_PointDetector
 * Method:    LandmarkNum
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_seeta_sdk_PointDetector_LandmarkNum
  (JNIEnv *, jobject);

/*
 * Class:     com_seeta_sdk_PointDetector
 * Method:    DetectCroppedLandmarks
 * Signature: (Lcom/seeta/sdk/ImageData;[Lcom/seeta/sdk/Point;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_seeta_sdk_PointDetector_DetectCroppedLandmarks
  (JNIEnv *, jobject, jobject, jobjectArray);

/*
 * Class:     com_seeta_sdk_PointDetector
 * Method:    DetectLandmarks
 * Signature: (Lcom/seeta/sdk/ImageData;Lcom/seeta/sdk/FaceInfo;[Lcom/seeta/sdk/Point;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_seeta_sdk_PointDetector_DetectLandmarks
  (JNIEnv *, jobject, jobject, jobject, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
