/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_seeta_sdk_SEETAPassiveFAS */

#ifndef _Included_com_seeta_sdk_SEETAPassiveFAS
#define _Included_com_seeta_sdk_SEETAPassiveFAS
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_seeta_sdk_SEETAPassiveFAS
 * Method:    getLog
 * Signature: ([D)V
 */
JNIEXPORT void JNICALL Java_com_seeta_sdk_SEETAPassiveFAS_getLog
  (JNIEnv *, jobject, jdoubleArray);

/*
 * Class:     com_seeta_sdk_SEETAPassiveFAS
 * Method:    construct
 * Signature: (Ljava/lang/String;IIDDIII)V
 */
JNIEXPORT void JNICALL Java_com_seeta_sdk_SEETAPassiveFAS_construct
  (JNIEnv *, jobject, jstring, jint, jint, jdouble, jdouble, jint, jint, jint);

/*
 * Class:     com_seeta_sdk_SEETAPassiveFAS
 * Method:    DetectCore
 * Signature: (Lcom/seeta/sdk/ImageData;Lcom/seeta/sdk/FaceInfo;[Lcom/seeta/sdk/Point;)I
 */
JNIEXPORT jint JNICALL Java_com_seeta_sdk_SEETAPassiveFAS_DetectCore
  (JNIEnv *, jobject, jobject, jobject, jobjectArray);

/*
 * Class:     com_seeta_sdk_SEETAPassiveFAS
 * Method:    ResetCore
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_seeta_sdk_SEETAPassiveFAS_ResetCore
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_seeta_sdk_SEETAPassiveFAS
 * Method:    SetActionsCore
 * Signature: ([I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_seeta_sdk_SEETAPassiveFAS_SetActionsCore
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     com_seeta_sdk_SEETAPassiveFAS
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_seeta_sdk_SEETAPassiveFAS_dispose
  (JNIEnv *, jobject);
  
  /*
 * Class:     com_seeta_sdk_SEETAPassiveFAS
 * Method:    getSnapshot
 * Signature: ()Lcom/seeta/sdk/ImageData;
 */
JNIEXPORT jobject JNICALL Java_com_seeta_sdk_SEETAPassiveFAS_getSnapshot
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
